// Shared "one level deeper into Edit Profile" host for fields that need
// selection or multi-entry editing (Primary/Secondary Role, Education &
// Training, Tools, Languages) -- one responsive component instead of a
// bottom sheet that stops halfway on mobile:
//
//   Mobile  (< lg): full-screen page, 100% of the viewport, slides IN from
//                   the RIGHT and back OUT to the right on close -- native
//                   iOS push-navigation, not a bottom-sheet slide.
//   Desktop (>= lg): a right-side panel (480-600px), slides IN from the
//                   right with the Edit Profile page behind it dimmed and
//                   non-interactive, slides back OUT on close.
//
// Same component for both breakpoints (per spec: "Use the same component
// for Secondary Role, Tools and Languages, changing only the content"),
// same way BottomSheet already covers mobile-sheet vs desktop-modal from
// one implementation. Mounted/unmounted by the caller (AboutEditor /
// ProfessionPicker) exactly like PortfolioItemFocusView -- kept mounted
// while (open || closing) so the exit animation can play before onClose
// actually unmounts it.
//
// `depth` lets one of these be pushed on top of another (e.g. Education &
// Training's list -> Add/Edit Education -> Education/Training Type is 3
// nested levels) -- each level's z-index is computed from `depth` via
// inline style (a template-interpolated Tailwind arbitrary value like
// `z-[${n}]` never gets generated by the JIT scanner, so this can't be a
// className) rather than relying on portal/mount order, which is what
// actually caused the Education/Training Type sheet to render behind the
// Add/Edit Education page it was opened from.
import { useState, useEffect, useRef, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { ChevronLeft } from 'lucide-react';

export function EditProfileFieldPanel({ title, onClose, children, footer, closing, depth = 0 }: {
  title: string;
  /** Self-contained mode (no `closing` prop): call this to actually unmount
   * -- the panel plays its own exit animation first, then calls this.
   * Controlled mode (`closing` passed): this is instead the "start
   * closing" trigger (same contract as TrustProfileOverlay/
   * PortfolioItemFocusView's `closing`+`onClose` pair) -- the parent owns
   * the exit timing, e.g. so a save action can close the panel the same
   * way the header's back button does. Use controlled mode when something
   * other than the panel's own header can trigger a close (AboutEditor's
   * Education editor closes itself after a successful Save). */
  onClose: () => void;
  children: ReactNode;
  /** Right-aligned action area (e.g. a Save/Done button), sticky at the
   * bottom -- optional, since some fields (e.g. a pure picker list) commit
   * on tap and need no explicit save step. */
  footer?: ReactNode;
  closing?: boolean;
  /** 0 = pushed directly from Edit Profile. Increment by 1 for each
   * additional panel pushed on top of another one (e.g. Education &
   * Training's entries list is depth 0, its Add/Edit Education editor is
   * depth 1, that editor's Education/Training Type page is depth 2), so
   * nested panels always stack correctly regardless of mount order. */
  depth?: number;
}) {
  const controlled = closing !== undefined;
  // Entrance is local to this component in BOTH modes -- without the rAF
  // delay the panel would render already in its final on-screen position
  // on first paint, with nothing for the transition to animate from.
  const [entered, setEntered] = useState(false);
  const [internalClosing, setInternalClosing] = useState(false);
  const closedRef = useRef(false);

  useEffect(() => {
    requestAnimationFrame(() => requestAnimationFrame(() => setEntered(true)));
  }, []);

  const isClosing = controlled ? !!closing : internalClosing;
  const show = entered && !isClosing;

  const close = () => {
    if (controlled) { onClose(); return; }
    if (closedRef.current) return;
    closedRef.current = true;
    setInternalClosing(true);
    setTimeout(onClose, 300);
  };

  const backdropZ = 85 + depth * 2;
  const panelZ    = 86 + depth * 2;

  // Portaled to document.body -- every caller (AboutEditor's accordions,
  // ProfessionPicker) sits inside Profile.tsx's own push-page-enter/exit
  // overlay, whose `transform` (kept applied after the animation finishes
  // by animation-fill-mode: both) establishes a CSS containing block for
  // any `position: fixed` descendant. Rendered as a normal DOM child there,
  // this panel's "fixed inset-0" would be sized/positioned relative to
  // THAT overlay's own box instead of the real viewport -- exactly the bug
  // where the panel only covered the content area below the header instead
  // of the whole screen. Portaling sidesteps the transformed ancestor
  // entirely, same fix already used for card-level menus/sheets elsewhere.
  return createPortal((
    <>
      {/* Desktop-only dimmed, non-interactive backdrop -- mobile's page
          already covers the full viewport so no separate scrim is needed
          there (matches Edit Profile's own overlay, which has none either). */}
      <div
        className="hidden lg:block fixed inset-0 bg-black/30 transition-opacity duration-300"
        style={{ zIndex: backdropZ, opacity: show ? 1 : 0, pointerEvents: show ? 'auto' : 'none' }}
        onClick={close}
      />
      <div
        className={`fixed inset-0 lg:inset-y-0 lg:left-auto lg:right-0 bg-white flex flex-col lg:w-[560px] lg:max-w-[90vw] lg:shadow-2xl transform transition-transform duration-300 ease-out ${
          show ? 'translate-x-0' : 'translate-x-full'
        }`}
        style={{ zIndex: panelZ, paddingBottom: 'env(safe-area-inset-bottom)' }}
      >
        <div className="flex items-center gap-2 px-2 py-3 border-b border-gray-100 shrink-0" style={{ paddingTop: 'max(0.75rem, env(safe-area-inset-top))' }}>
          <button onClick={close} className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-gray-100 text-gray-600 shrink-0 -ml-0.5">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <p className="text-base font-black text-gray-900 truncate">{title}</p>
        </div>

        <div className="flex-1 overflow-y-auto">
          {children}
        </div>

        {footer && (
          <div className="shrink-0 px-4 py-3 border-t border-gray-100 flex justify-end">
            {footer}
          </div>
        )}
      </div>
    </>
  ), document.body);
}
